---
- name: Configure loopback 0 on router R1,R2,R3
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Configure loopback interface
      cisco.ios.ios_config:
        parents: interface loopback 0
        lines:
          - ip address 192.168.100.1 255.255.255.255
          - no shut
...
