[routers]
R1 ansible_host=172.16.166.131

[routers:vars]
ansible_user=admin
ansible_password=letmein
ansible_network_os=ios
ansible_become=yes
ansible_become_method=enable

[persistent_connection]
command_timeout = 120
