---
- name: Configure Loopback0 on R1
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Configure loopback0 interface
      cisco.ios.ios_config:
        parents: interface Loopback0
        lines:
          - description Configured using Ansible
          - ip address 192.168.100.1 255.255.255.255
          - no shutdown
      register: config_output

    - name: Show the config_output
      ansible.builtin.debug:
        msg: "{{ config_output.commands }}"
