---
- name: Configure NTP on Cisco devices
  hosts: cisco
  gather_facts: false
  connection: network_cli

  tasks:
    # Task to apply NTP configuration using Jinja2 template
    - name: Apply NTP configuration from Jinja2 template
      cisco.ios.ios_config:
        # Load NTP configuration from Jinja2 template using lines: and .splitlines for proper formatting
        lines: "{{ lookup('template', 'ntp.j2').splitlines() }}"
      register: ntp_config_result
    # Task to display the result of the NTP configuration
    - name: Display NTP configuration result
      ansible.builtin.debug:
        var: ntp_config_result
