---

- name: Backup configuration using specific commands
  hosts: cisco_switches
  gather_facts: false
  connection: network_cli

  tasks:
  - name: Capture specific show commands
    cisco.ios.ios_command:
      commands:
        - show ip arp
        - show ip interface brief
        - show mac address-table
    register: command_output

  - name: Save all command outputs to single file
    # Using the copy module to write the outputs to a file on the control node
    copy:
      content: |
        ========================================
        Device: {{ inventory_hostname }}
        ========================================
        # Using the captured command_output using [] to access each command's output
        === SHOW IP ARP ===
        {{ command_output.stdout[0] }}

        === SHOW IP INTERFACE BRIEF ===
        {{ command_output.stdout[1] }}

        === SHOW MAC ADDRESS-TABLE ===
        {{ command_output.stdout[2] }}
    # Specify the destination path on the control node
      dest: "/Users/apple/Desktop/GitHub/Ansible/Lab-15_Config_Backup_Commands/backup_{{ inventory_hostname }}.txt"
