---
- name: Configure loopbacks and static routes
  hosts: routers
  gather_facts: false
  connection: network_cli

  vars:
    loopback_mask: "255.255.255.255"

  tasks:
    - name: Configure loopbacks
      cisco.ios.ios_config:
        # This value will get pulled from the the routers.yml which is under group_vars folder.
        parents: "interface loopback {{ item.id }}" 
        lines:
          # This values will be also pulled from routers.yml which is under group_vars folder.
          - " description {{ item.des }}" 
          # The values will be pulled from the host_vars folder where we have loopback_ips configured and .id means the loopback id number.
          - "ip address {{ hostvars[inventory_hostname].loopback_ips[item.id] }} {{ loopback_mask }}"
          - "no shut"

      loop:
      loop_control:
        label: "Loopback{{ item.id }}"

    # - name: Add static routes
    #   cisco.ios.ios_config:
    #     lines:
    #       - "ip route {{ item.dest }} {{item.next_hop}}"
      
    #   loop: "{{ static_routes }}"

