[vyos]
VyOs1 ansible_host=172.16.166.132

[vyos:vars]
ansible_user=vyos
ansible_password=vyos
ansible_network_os=vyos
ansible_connection=network_cli
ansible_become=yes
ansible_become_method=enable
ansible_command_timeout=120
