---
loopback_ips:
  # Define ip address for this router loopback
  1: "10.2.2.1"
  2: "10.2.2.2"

static_routes:
  # Static routes for R2
  - dest: "10.1.1.0 255.255.255.0"
  - next_hop: "10.255.1.101"